{% set name = "google-cloud-datastore" %}
{% set version = "2.20.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9665d009729d9551329d9476f4d5bda9c11d3469243ea8a2c0d9490b65aa899f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - google-api-core >=1.34.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0dev,!=2.24.0,!=2.25.0
    - google-cloud-core >=1.4.0,<3.0.0dev
    # more restrictive constraint for python >= 3.11
    - proto-plus >=1.22.2,<2.0.0dev
    - protobuf >=3.20.2,<6.0.0dev,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - google
    - google.cloud
    - google.cloud.datastore
    - google.cloud.datastore_v1
    - google.cloud.datastore_admin_v1
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/googleapis/python-datastore
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python Client for Google Cloud Datastore
  description: |
    Google Cloud Datastore API is a fully managed, schemaless database for
    storing non-relational data. Cloud Datastore automatically scales with
    your users and supports ACID transactions, high availability of reads
    and writes, strong consistency for reads and ancestor queries, and
    eventual consistency for all other queries.
  doc_url: https://googleapis.dev/python/datastore/latest
  dev_url: https://github.com/googleapis/python-datastore

extra:
  recipe-maintainers:
    - xylar
    - mathiaseitz
    - trendelkampschroer
    - parthea
