{% set name = "google-cloud-datastore" %}
{% set version = "1.15.1" %}
{% set sha256 = "4dbd375de6ae8cff855cecf4ff9565de9c7faf4dc8da8a4e53fbd2a5c6d28624" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - google-cloud-core >=1.4.0, < 2.0dev
    - google-api-core-grpc >=1.14.0, < 2.0.0dev

test:
  imports:
    - google
    - google.cloud
    - google.cloud.datastore

about:
  home: https://github.com/GoogleCloudPlatform/google-cloud-python
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python Client for Google Cloud Datastore
  description: |
    Google Cloud Datastore API is a fully managed, schemaless database for
    storing non-relational data. Cloud Datastore automatically scales with
    your users and supports ACID transactions, high availability of reads
    and writes, strong consistency for reads and ancestor queries, and
    eventual consistency for all other queries.
  doc_url: https://googleapis.github.io/google-cloud-python/latest/datastore/index.html
  dev_url: https://github.com/GoogleCloudPlatform/google-cloud-python

extra:
  recipe-maintainers:
    - mathiaseitz
    - trendelkampschroer
