{% set name = "google-cloud-datastore" %}
{% set version = "2.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-datastore-{{ version }}.tar.gz
  sha256: 63b31b676dcb2786a650d23d324d8f886c4e14586afdd0cfe6e260a73f12448e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - google-api-core-grpc >=1.34.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-cloud-core >=1.4.0,<3.0.0dev
    - proto-plus >=1.22.0,<2.0.0dev
    - protobuf >=3.19.5,<5.0.0dev,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - google
    - google.cloud
    - google.cloud.datastore
    - google.cloud.datastore_v1
    - google.cloud.datastore_admin_v1
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-datastore
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python Client for Google Cloud Datastore
  description: |
    Google Cloud Datastore API is a fully managed, schemaless database for
    storing non-relational data. Cloud Datastore automatically scales with
    your users and supports ACID transactions, high availability of reads
    and writes, strong consistency for reads and ancestor queries, and
    eventual consistency for all other queries.
  doc_url: https://googleapis.dev/python/datastore/latest
  dev_url: https://github.com/googleapis/python-datastore

extra:
  recipe-maintainers:
    - xylar
    - mathiaseitz
    - trendelkampschroer
    - parthea
